name: Github Actions Releaser
description: Create a release notes using gren
author: raulanatol
branding:
  color: green
  icon: upload-cloud
inputs:
  GITHUB_TOKEN:
    description: The github token
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
